export const RESET_API_SELECTION_VALUE = 'RESET_API_SELECTION';
export type RESET_API_SELECTION = typeof RESET_API_SELECTION_VALUE;

export const SET_API_SELECTION_VALUE = 'SET_API_SELECTION';
export type SET_API_SELECTION = typeof SET_API_SELECTION_VALUE;
