export const RESET_USER_STORE_VALUE = 'RESET_USER_STORE';
export type RESET_USER_STORE = typeof RESET_USER_STORE_VALUE;

export const SET_USER_STORE_VALUE = 'SET_USER_STORE';
export type SET_USER_STORE = typeof SET_USER_STORE_VALUE;
