version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: ['npm', 'dependencies', 'dependabot', 'impact: maintainers']
    ignore:
      # Version 5.0.0 no longer the LocationDescriptor and locationState types introducing breaking
      # changes in the react-router-dom and in our application. React-router-dom needs version
      # 4.10.1
      - dependency-name: history
      # @department-of-veterans-affairs/formation library depends on resources that the uswds
      # library has removed or moved in its latest version. This external dependency breaking
      # change does not allow us to upgrade to the latest version
      - dependency-name: uswds
      # Errorable elements are not available in the latest version. Application would need to be
      # refactored to integrate the new available elements
      - dependency-name: '@department-of-veterans-affairs/formation-react'
      # Previous packages preventing updates to puppeteer have been updated
      # Upgrade ticket: https://jira.devops.va.gov/browse/API-28858
      - dependency-name: puppeteer
      # Latest version is incompatible with current codebase.
      # Audit/upgrade ticket: https://jira.devops.va.gov/browse/API-28854
      - dependency-name: immutable
        versions: [4.0.0-rc.x]
