# This release file uses the new git hub cli tool called gh to automate release and artifact uploade.
# Learn more here; https://github.com/cli/cli
version: 0.2
env:
  variables:
    ENVS: "dev staging production"
    S3_ARCHIVE_BUCKET: "developer-portal-builds-s3-upload"
    BUILD: "true"
  parameter-store:
    GITHUB_TOKEN: "/dvp/devops/va_bot_github_token"
    SLACK_WEBHOOK: "/dvp/devops/codebuild_slack_webhook"
phases:
  pre_build:
    commands:
      - gh config set prompt disabled
      - gh config set git_protocol ssh
      - COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Generating release for ${COMMIT_HASH}" 
  build:
    commands:
      # Check CI status of current commit hash
      - ci_status=$(gh api /repos/department-of-veterans-affairs/developer-portal/commits/${COMMIT_HASH}/status | jq -r .state)
      - echo ${ci_status}
      - |
        while [[ ${ci_status} == "pending" ]]; do
          echo "CI still running -- sleep"
          ci_status=$(gh api /repos/department-of-veterans-affairs/developer-portal/commits/${COMMIT_HASH}/status | jq -r .state)
          echo ${ci_status}
          sleep 10
        done
      - |
        if [[ ${ci_status} ]] != "success" ]]; then
          echo "CI failed release aborted"
          exit 1
        fi
      - mkdir -p release
      - aws s3 sync --no-progress s3://${S3_ARCHIVE_BUCKET}/cb-${COMMIT_HASH} release/.
      # Check that all files exist 
      - | 
        for env in ${ENVS}; do
          if [[ ! -f release/${env}.tar.bz2 ]]; then
            echo "${env}.tar.bz2 was not found. Aborting release process and sending notification to slack " >&2
            exit 1
          fi
        done
      # Create new tag
      - OLD_TAG=$(git tag --sort=-creatordate | grep cb- | head -1)
      - echo "Found ${OLD_TAG} - incrementing..."
      - NEW_TAG=$(increment.sh ${OLD_TAG}) 
      - echo "Creating ${NEW_TAG} release"
      - gh release create ${NEW_TAG}
      - echo "Uploading artifacts"
      - |
        for env in ${ENVS}; do
          gh release upload ${NEW_TAG} "release/${env}.tar.bz2#{NEW_TAG}_${env}.tar.bz2"
          echo "${env} artifact uploaded"
        done
      # - | 
      #   if [[ ${BUILD} == "true" ]]; then
      #     aws codebuild start-build --project-name devportal-deploy --environment-variables-override name=ENVS,value=dev name=RELEASE,value=${NEW_TAG}
      #   fi
  post_build:
    commands:
      # Post to Slack if failure.
      if [[ CODEBUILD_BUILD_SUCCEEDING -eq 0 ]]; then
        slackpost.sh "There was an error with the release process for ${CODEBUILD_BUILD_ID}."
      fi
