######################################################################
#  Developer Portal Review Deploy
#
#
# Tool Links:
#  - CodeBuild - https://docs.aws.amazon.com/codebuild/index.html
#  - CodeBuild Environmental Variables - https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
#  - Runner for CodeBuild Enironment - https://github.com/department-of-veterans-affairs/lighthouse-codebuild-containers/tree/main/docker-runner
#  - AWS CLI 2.0 - https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html
#
# All Custom scripts are on the CodeBuild Environment container.
# https://github.com/department-of-veterans-affairs/lighthouse-codebuild-containers/tree/main/
#
# Custom Scripts:
#  - pr-verify.sh
#  - pr-number.sh
#
######################################################################
version: 0.2
env:
  shell: bash
  variables:
    GITHUB_USERNAME: 'va-bot'
    # These are the test make targets.
    ENVIRONMENTS: 'dev staging production'
    # Bucket for archiving deployments
    S3_REVIEW_BUCKET: 'review-developer-va-gov'
    ## move to paramstore
    PREVIEW_SENTRY_DSN: 'http://dc7d5ebec20e474c80f8150c399d2955@sentry.vfs.va.gov/26'
    # Setting REPO
    REPO: 'developer-portal'
    # Exclude this check from CI Status
    XCHECKS: 'developer-portal-review-deploy'
    # Running the container as root.
    UNAME: root
    GNAME: root
    # Sentry
    SENTRY_ORG: 'vsp'
    SENTRY_PROJECT: 'dvp-developer-portal-web'
    SENTRY_URL: 'http://sentry.vfs.va.gov/'
  parameter-store:
    GITHUB_TOKEN: '/dvp/devops/va_bot_github_token'
    DOCKER_USERNAME: '/dvp/devops/DOCKER_USERNAME'
    DOCKER_PASSWORD: '/dvp/devops/DOCKER_PASSWORD'
    # Sentry
    SENTRY_DSN: '/dvp/devops/SENTRY_DSN/developer-portal-frontend'
    SENTRY_AUTH_TOKEN: '/dvp/devops/SENTRY_AUTH_TOKEN'
phases:
  install:
    commands:
      # There is considerable slow down in the provisioning phase when using Amazon provided images.
      # Therefore we use our own Alpine based image. In order to activate the Docker Daemon these lines are needed.
      - /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      # Install sentry-cli tool
      - curl -sL https://sentry.io/get-cli/ | bash
      - sentry-cli info --log-level=info
      # Make a url compliant name for S3
      # Short Ref to commit hash
      - COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      # Verify PR is coming from source repository
      - pr-verify.sh -r ${REPO} -c ${COMMIT_HASH}
      # Get PR Num
      - PRNUM=$(pr-number.sh -r ${REPO}  -c ${COMMIT_HASH})
      - |
        if [[ -z ${PRNUM} ]]; then
          echo "No PR Found aborting job"
          exit 1
        fi
      # Log all environment varbiables to cloudwatch in case we need to troubleshoot. AWS is nice enough to hide any secrets from parameter-store.
      - printenv
      # Login to Docker Hub prior to pulling Dockerfile's base image node:12. This prevents rate limiting from Docker Hub.
      - echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      # Create the required dot files prior to build for proper deployment to review bucket
      - |
        for env in ${ENVIRONMENTS}; do
        cat <<EOF > .env.${env}.local
        PUBLIC_URL=/${S3_REVIEW_BUCKET}/${COMMIT_HASH}/${env}
        REACT_APP_SENTRY_DSN=${PREVIEW_SENTRY_DSN}
        EOF
        done
      - make build
  build:
    commands:
      - links=""
        # Run build and generate links per environment
      - |
        for env in ${ENVIRONMENTS}; do
          make build_app ENVIRONMENT=${env} || exit 1
          links="${links} - [${env}](https://s3-us-gov-west-1.amazonaws.com/${S3_REVIEW_BUCKET}/${COMMIT_HASH}/${env}/index.html) <br>"
        done
      # Create deploy.json per environment
      - |
        for env in ${ENVIRONMENTS}; do
          date > ./current-date
          echo '{' > build/${env}/deploy.json
          echo "  \"environment\": \"${env}\"," >> build/${env}/deploy.json
          echo "  \"date\": \"$( cat current-date )\"," >> build/${env}/deploy.json
          echo "  \"commit\": \"${COMMIT_HASH:0:7}\"" >> build/${env}/deploy.json
          echo '}' >> build/${env}/deploy.json
          rm ./current-date
        done
      # Deploy To s3 review bucket
      - aws s3 sync --no-progress --acl public-read build/ s3://${S3_REVIEW_BUCKET}/${COMMIT_HASH}/
      - |
        comment="these changes have been deployed to an s3 bucket. a build for each environment is available: <br><br> ${links} <br> due to s3 website hosting limitations in govcloud you need to first navigate to index.html explicitly."
      - gh pr comment ${PRNUM} --body "${comment}"
