name: API-19692 Cypress Infrastructure Updates

on:
  push:
    branches:
      - 'API-19692-update-cypress-tests-ci-infrastructure'

jobs:
  accessibility:
    runs-on: ubuntu-latest
    container: cypress/included:9.6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python env
        run: |
          apt update && apt install python3 -y && ln -s /usr/bin/python3 /usr/bin/python

      - name: Start Fake LPB Server
        run: ./scripts/fake_lpb.sh

      - name: Run an npm install
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config: ignoreTestFiles=null
          # we have already installed all dependencies above
          install: false
          spec: cypress/integration/accessibility.spec.js
          start: npm start
          wait-on: http://localhost:3001
          wait-on-timeout: 120
