name: API-19692 Cypress Infrastructure Updates

on:
  push:
    branches:
      - 'API-19692-update-cypress-tests-ci-infrastructure'

jobs:
  accessibility:
    runs-on: ubuntu-latest
    container: cypress/included:9.6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'

      - name: Set up Python 3.9
        run: |
          apt update
          apt-get install -y software-properties-common 
          add-apt-repository -y ppa:deadsnakes/ppa
          apt-get install -y python3.9
          ln -s `which python3.9` /usr/local/bin/python
          python --version

      - name: Start Fake LPB Server
        run: ./scripts/fake_lpb.sh

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config: ignoreTestFiles=null
          # we have already installed all dependencies above
          install: false
          spec: cypress/integration/accessibility.spec.js
          start: npm start
          wait-on: http://localhost:3001
          wait-on-timeout: 120
