name: API-19692 Cypress Infrastructure Updates

on:
  push:
    branches:
      - 'api-19692/node-18-cypress-in-docker'

env:
  REACT_APP_VETSGOV_SWAGGER_API: http://localhost:3001

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    container: cypress/included:12.8.1
    outputs:
      node_version: ${{ steps.node_version.outputs.node_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - id: node_version
        name: Set Node Version to ENV
        run: |
          env
          NODE_VERSION=$(node -v)
          echo $NODE_VERSION
          echo "::set-output name=node_version::$NODE_VERSION"

      - name: Install python env
        run: |
          apt update && apt install python3 -y && ln -s /usr/bin/python3 /usr/bin/python
      - name: Install bzip2
        run: apt install bzip2

      - name: Start Fake LPB Server
        run: ./scripts/fake_lpb.sh

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: npm ci --legacy-peer-deps
          start: npm start
          wait-on: http://localhost:3001
          wait-on-timeout: 180

      - name: Upload failed screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload failed videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

  accessibility:
    runs-on: ubuntu-latest
    container: cypress/included:12.8.1
    outputs:
      node_version: ${{ steps.node_version.outputs.node_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - id: node_version
        name: Set Node Version to ENV
        run: |
          env
          NODE_VERSION=$(node -v)
          echo $NODE_VERSION
          echo "::set-output name=node_version::$NODE_VERSION"

      - name: Install python env
        run: |
          apt update && apt install python3 -y && ln -s /usr/bin/python3 /usr/bin/python
      - name: Install bzip2
        run: apt install bzip2

      - name: Start Fake LPB Server
        run: ./scripts/fake_lpb.sh

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          env: CYPRESS_SINGLE_SPEC=true
          install-command: npm ci --legacy-peer-deps
          spec: cypress/integration/accessibility.cy.js
          start: npm start
          wait-on: http://localhost:3001
          wait-on-timeout: 180

      - name: Upload failed screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload failed videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
