name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_run:
    workflows: ['Automatically label PRs with content changes']
    types:
      - completed

jobs:
  is_labeled:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: 'impact: users, impact: maintainers'
